FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY ["CourseAPI/CourseAPI.csproj", "CourseAPI/"]
COPY ["Services/Services.csproj", "Services/"]
COPY ["Application/Application.csproj", "Application/"]
COPY ["Domain/Domain.csproj", "Domain/"]
RUN dotnet restore "CourseAPI/CourseAPI.csproj"
COPY . .
WORKDIR "/src/CourseAPI"
RUN dotnet build "CourseAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CourseAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CourseAPI.dll"]